### ISSUE TITLE
Display multi-channel track, how can I do?

### ISSUE THREAD

**Issue by qiu0130** [1j01/wavey#1]
I need to display multi-channel track, I do not know the web API can be support?

**Comment by 1j01** [comment]
For now I've just been displaying a single channel for simplicity, but multi-channel display is planned.
Are you asking for this in Wavey or for how to implement this in another project?

As to how this should work...
Audacity just displays the channels in a vertical stack, which is "simple" but means some tracks take up twice the height and the information density is pretty low. One possibility is overlaying the channel waveforms, and it could use a filter like multiply to avoid the issue of "which goes on top", but so far Wavey is generally as functional in monochrome as not, so I'm hesitant to use two colors here (three if they're multiplied). Another possibility is to forego the raw display of the waveform for an indication of "loudness", in which case it could display the channels as a graph out from the middle. Mono tracks would  just be symmetrical, the same height as stereo tracks. That seems like a good option because the raw waveform rarely tells you much other than the "loudness" and it doesn't even do that very well since it just displays the raw amplitude, not really in line with how humans perceive loudness.

I've been thinking about this a bit lately. 😄

**Comment by qiu0130** [comment]
First,thanks for your answer.

I need to display multi-channel track in Wavey,But not quite understand how to do.

Now, I have a problem
I don't need to display the history tracks, how stop load local cache track or clean it?









ps:I'm a novice.:smile:

**Comment by 1j01** [comment]
Wavey is in an alpha state right now; I should probably have the readme reflect that. Even I haven't been able to use it for much of anything yet.
If you import multi-channel tracks, the stereo track data should be retained (i.e. if you export it should still be in stereo), but as of yet there's no way to display the multiple channels.

I was confused as to what you meant by "history tracks" or "local cache track", but I'm guessing you mean the tracks from a previous session.
You can remove tracks with the X button (which can be undone), or you can just start a new document (leaving the old one intact) by adding a hash like https://audioeditor.ml#document=new-doc-1
To actually delete the audio data currently you have to clear out everything for https://audioeditor.ml via your browser's settings. I do intend to implement proper document management though!

**Comment by qiu0130** [comment]
Thank you for solving my problem.

I will continue to pay attention to this project and learn it.
Looking forward to more  document management!
